spring:
  hadoop:
    #fsUri: hdfs://localhost:8020
    resourceManagerHost: localhost
  #is it really necessary to keep all this file in config?
    resources:
      - file:/etc/hadoop/2.6.5.0-292/0/core-site.xml
      - file:/etc/hadoop/2.6.5.0-292/0/yarn-site.xml
      - file:/etc/hadoop/2.6.5.0-292/0/hdfs-site.xml
  yarn:
    appName: replicator-${flow.id}
    applicationDir: /apps/replicator/app
    appmaster:
      appmaster-class: appmaster.ReplicatorAppmaster
      launchcontext:
        archiveFile: replicator-container-1.0-SNAPSHOT.jar