spring:
  hadoop:
    fsUri: hdfs://localhost:9000
    resourceManagerHost: localhost
  #is it really necessary to keep all this file in config?
  resources:
    - file:/etc/hadoop/conf/core-site.xml
    - file:/etc/hadoop/conf/yarn-site.xml
    - file:/etc/hadoop/conf/hdfs-site.xml
    - file:/etc/hadoop/conf/hbase-site.xml
  yarn:
    appName: replicator-${flow.id}
    #mb /user/${user.name}?
    applicationDir: /apps/replicator/app
    client:
      files:
        - "file:build/lib/replicator-appmaster.jar"
        - "file:build/lib/replicator-container.jar"
      localizer:
        patterns:
          - "*.jar"
          - "*.yml"
          - "*.properties"
      launchcontext:
        archiveFile: replicator-appmaster.jar
        options:
          - -Dflow.id=${flow.id:$$}
    appmaster:
      containerCount: 1
      launchcontext:
        archiveFile: replicator-container.jar
        arguments:
          --my.container.arg1: 1