spring:
  hadoop:
    fsUri: hdfs://localhost:9000
    resourceManagerHost: localhost
  yarn:
    appName: replicator-${flow.id}
    applicationDir: /apps/replicator/app
    client:
      files:
        - "file:build/lib/replicator-appmaster.jar"
        - "file:build/lib/replicator-container.jar"
      launchcontext:
        archiveFile: replicator-appmaster.jar
    appmaster:
      containerCount: 1
      launchcontext:
        archiveFile: replicator-container.jar
        arguments:
          --my.container.arg1: 1